version: '3.8'
services:
  backend:
    restart: always
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - '3000:3000'
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
    restart: always
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    restart: always
volumes:
  mongo:
  redis:
